<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PlateformSeeder extends Seeder
{
    public function run()
    {
        $data = [
        [        
            'id' => '1',
            'slug' => 'applemusic',
            'type' => 'portfolio',
            'name' => 'Apple Music',
            'hints' => 'Playlist / Album Link',
            'instruction' => 'Pick your favorite playlist/track/album and tap three dots in the top right corner. Tap share and copy/paste link here.',
            'image' => 'applemusic.png',
            'baseURL' => '',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'applemusicB.png',
            'roundImage' => 'applemusicR.png',
            'roundBlurImage' => 'applemusicBR.png'
        ],
        [
            'id' => '2',
            'slug' => 'behance',
            'type' => 'portfolio',
            'name' => 'Behance',
            'hints' => 'Username',
            'instruction' => 'Navigate to your avatar in the top right corner, a drop-down menu will appear. Click Settings. Click the Account Information tab.',
            'image' => 'behance.png',
            'baseURL' => 'https://',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'behanceB.png',
            'roundImage' => 'behanceR.png',
            'roundBlurImage' => 'behanceBR.png'
        ],[
            'id' => '3',
            'slug' => 'daviplata',
            'type' => 'finance',
            'name' => 'Daviplata',
            'hints' => 'Link',
            'instruction' => '',
            'image' => 'daviplata.png',
            'baseURL' => '',
            'profileURL' => 'daviplata://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'daviplataB.png',
            'roundImage' => 'daviplataR.png',
            'roundBlurImage' => 'daviplataBR.png'
        ],[
            'id' => '4',
            'slug' => 'email',
            'type' => 'contact',
            'name' => 'Email',
            'hints' => 'Email',
            'instruction' => 'Input your email address. This email can be the same of different from the one used for your account signup.',
            'image' => 'email.png',
            'baseURL' => 'mailto:',
            'profileURL' => 'mailto:',
            'inputType' => 'email',
            'status' => '1',
            'blurImage' => 'emailB.png',
            'roundImage' => 'emailR.png',
            'roundBlurImage' => 'emailBR.png'
        ],[
            'id' => '5',
            'slug' => 'facebook',
            'type' => 'social',
            'name' => 'Facebook',
            'hints' => 'Facebook Profile Link',
            'instruction' => 'Go to facebook and open your Facebook profile or page. Under your name there is three dotes, click on it. Then copy your profile link and paste the link here.',
            'image' => 'facebook.png',
            'baseURL' => 'https://www.facebook.com/',
            'profileURL' => 'fb://facewebmodal/f?href=',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'facebookB.png',
            'roundImage' => 'facebookR.png',
            'roundBlurImage' => 'facebookBR.png'
        ],[
            'id' => '6',
            'slug' => 'github',
            'type' => 'portfolio',
            'name' => 'Github',
            'hints' => 'Github Link',
            'instruction' => 'Tap in your profile icon and it will show you your username as “Signed in as user_name”. Copy your username and paste it here.',
            'image' => 'github.png',
            'baseURL' => '',
            'profileURL' => 'github://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'githubB.png',
            'roundImage' => 'githubR.png',
            'roundBlurImage' => 'githubBR.png'
        ],[
            'id' => '7',
            'slug' => 'gmail',
            'type' => 'contact',
            'name' => 'Gmail',
            'hints' => 'Email ID',
            'instruction' => 'Input your email address. This email can be the same of different from the one used for your account signup.',
            'image' => 'gmail.png',
            'baseURL' => '',
            'profileURL' => 'gmail://',
            'inputType' => 'email',
            'status' => '1',
            'blurImage' => 'gmailB.png',
            'roundImage' => 'gmailR.png',
            'roundBlurImage' => 'gmailBR.png'
        ],[
            'id' => '8',
            'slug' => 'instagram',
            'type' => 'social',
            'name' => 'Instagram',
            'hints' => 'Username without @',
            'instruction' => 'Open the Instagram app and go to your profile. Your Instagram username will be at the top of your screen.',
            'image' => 'instagram.png',
            'baseURL' => 'https://www.instagram.com/',
            'profileURL' => 'instagram://user?username=',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'instagramB.png',
            'roundImage' => 'instagramR.png',
            'roundBlurImage' => 'instagramBR.png'
        ],[
            'id' => '9',
            'slug' => 'link',
            'type' => 'other',
            'name' => 'Link website',
            'hints' => 'Custom link',
            'instruction' => 'Open your desired website and copy/paste the url here.',
            'image' => 'link.png',
            'baseURL' => '',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'link.pngB',
            'roundImage' => 'link.pngR',
            'roundBlurImage' => 'linkBR.png'
        ],[
            'id' => '10',
            'slug' => 'linkedin',
            'type' => 'social',
            'name' => 'LinkedIn',
            'hints' => 'Linkedin Profile url',
            'instruction' => 'Go to your Linkedin profile and scroll down to the “contact” section. Find your Linkedin profile link and copy/paste here!',
            'image' => 'linkedin.png',
            'baseURL' => 'https://www.linkedin.com/in/',
            'profileURL' => 'linkedin://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'linkedinB.png',
            'roundImage' => 'linkedinR.png',
            'roundBlurImage' => 'linkedinBR.png'
        ],[
            'id' => '11',
            'slug' => 'maps',
            'type' => 'business',
            'name' => 'Maps',
            'hints' => 'Address Here',
            'instruction' => 'Open Apple Maps and find the Location. Tap the share button in the top right and copy here!',
            'image' => 'maps.png',
            'baseURL' => 'http://maps.google.co.in/maps?q=',
            'profileURL' => 'http://maps.google.co.in/maps?q=',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'mapsB.png',
            'roundImage' => 'mapsR.png',
            'roundBlurImage' => 'mapsBR.png'
        ],[
            'id' => '12',
            'slug' => 'medium',
            'type' => 'portfolio',
            'name' => 'Medium',
            'hints' => 'Medium Link',
            'instruction' => 'Tap in your profile and then select “Settings” from the 3 dots on the top right corner. Then tap in “Account” and you should see your medium URL. Copy and paste it here',
            'image' => 'medium.png',
            'baseURL' => '',
            'profileURL' => 'medium://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'mediumB.png',
            'roundImage' => 'mediumR.png',
            'roundBlurImage' => 'mediumBR.png'
        ],[
            'id' => '13',
            'slug' => 'nequi',
            'type' => 'finance',
            'name' => 'Nequi',
            'hints' => 'Nequi Link',
            'instruction' => '',
            'image' => 'nequi.png',
            'baseURL' => '',
            'profileURL' => 'nequi://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'nequiB.png',
            'roundImage' => 'nequiR.png',
            'roundBlurImage' => 'nequiBR.png'
        ],[
            'id' => '14',
            'slug' => 'outlook',
            'type' => 'contact',
            'name' => 'Outlook',
            'hints' => 'Email Address',
            'instruction' => 'Input your email address. This email can be the same of different from the one used for your account signup.',
            'image' => 'outlook.png',
            'baseURL' => '',
            'profileURL' => 'outlook://',
            'inputType' => 'email',
            'status' => '1',
            'blurImage' => 'outlookB.png',
            'roundImage' => 'outlookR.png',
            'roundBlurImage' => 'outlookBR.png'
        ],[
            'id' => '15',
            'slug' => 'paypal',
            'type' => 'finance',
            'name' => 'Paypal',
            'hints' => 'Email Address or Payment Link',
            'instruction' => 'Go to setting. Then to paypal.me and tap “Create your PayPal.Me Link” Copy/paste here! [example: paypal.me/username]',
            'image' => 'paypal.png',
            'baseURL' => 'https://www.paypal.me/',
            'profileURL' => 'https://www.paypal.com/paypalme/',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'paypalB.png',
            'roundImage' => 'paypalR.png',
            'roundBlurImage' => 'paypalBR.png'
        ],[
            'id' => '16',
            'slug' => 'phone',
            'type' => 'contact',
            'name' => 'Phone',
            'hints' => 'Phone Number',
            'instruction' => 'Enter your phone number. Make sure to include your country code!',
            'image' => 'phone.png',
            'baseURL' => 'tel:',
            'profileURL' => 'tel:',
            'inputType' => 'phone',
            'status' => '1',
            'blurImage' => 'phoneB.png',
            'roundImage' => 'phoneR.png',
            'roundBlurImage' => 'phoneBR.png'
        ],[
            'id' => '17',
            'slug' => 'pinterest',
            'type' => 'social',
            'name' => 'Pinterest',
            'hints' => 'Username',
            'instruction' => 'Click on your profile picture at the top left corner of your screen. Your username can be found under your full name, preceded by “@”. [Don’t include the @ here',
            'image' => 'pinterest.png',
            'baseURL' => 'https://www.pinterest.com/',
            'profileURL' => 'pinterest://www.pinterest.com/',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'pinterestB.png',
            'roundImage' => 'pinterestR.png',
            'roundBlurImage' => 'pinterestBR.png'
        ],[
            'id' => '18',
            'slug' => 'soundcloud',
            'type' => 'portfolio',
            'name' => 'Soundcloud',
            'hints' => 'SoundCloud @Username',
            'instruction' => 'Open the Soundcloud app and go to library then Click on Profile pic at top Right corner.Cick on Profile tab.There share button Click on it And  Copy and paste here.',
            'image' => 'soundcloud.png',
            'baseURL' => '',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'soundcloudB.png',
            'roundImage' => 'soundcloudR.png',
            'roundBlurImage' => 'soundcloudBR.png'
        ],[
            'id' => '19',
            'slug' => 'spotify',
            'type' => 'portfolio',
            'name' => 'Spotify',
            'hints' => 'Username',
            'instruction' => 'Open Spotify and click a song, album, artist, or playlist. Click the three dots in the top right corner, click share, click Copy Link, and paste the link here.',
            'image' => 'spotify.png',
            'baseURL' => 'https://open.spotify.com/user/',
            'profileURL' => 'open.spotify.com/',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'spotifyB.png',
            'roundImage' => 'spotifyR.png',
            'roundBlurImage' => 'spotifyBR.png'
        ],[
            'id' => '20',
            'slug' => 'tiktok',
            'type' => 'social',
            'name' => 'Tiktok',
            'hints' => 'Username without @',
            'instruction' => 'Open TikTok and go to the “me” tab. Your TikTok username is under your profile picture.',
            'image' => 'tiktok.png',
            'baseURL' => 'https://www.tiktok.com/',
            'profileURL' => 'https://www.tiktok.com/@',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'tiktokB.png',
            'roundImage' => 'tiktokR.png',
            'roundBlurImage' => 'tiktokBR.png'
        ],[
            'id' => '21',
            'slug' => 'tripadvisor',
            'type' => 'business',
            'name' => 'Trip Advisor',
            'hints' => 'Trip advisor profile url',
            'instruction' => 'Go to the listing you want to share, tapp on the share icon and press “Copy Link”. Paste the listing’s link here.',
            'image' => 'tripadvisor.png',
            'baseURL' => '',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'tripadvisorB.png',
            'roundImage' => 'tripadvisorR.png',
            'roundBlurImage' => 'tripadvisorBR.png'
        ],[
            'id' => '22',
            'slug' => 'twitch',
            'type' => 'social',
            'name' => 'Twitch',
            'hints' => 'Username without @',
            'instruction' => 'Open Twitch and click the profile icon in the top left corner. Your username is at the top.',
            'image' => 'twitch.png',
            'baseURL' => '',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'twitchB.png',
            'roundImage' => 'twitchR.png',
            'roundBlurImage' => 'twitchBR.png'
        ],[
            'id' => '23',
            'slug' => 'twitter',
            'type' => 'social',
            'name' => 'Twitter',
            'hints' => 'Username without @',
            'instruction' => 'Open the Twitter app and tap your profile picture in the top left corner.Your Twitter username will be in grey with an @ sign.',
            'image' => 'twitter.png',
            'baseURL' => 'https://twitter.com/',
            'profileURL' => 'twitter://user?screen_name=',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'twitterB.png',
            'roundImage' => 'twitterR.png',
            'roundBlurImage' => 'twitterBR.png'
        ],[
            'id' => '24',
            'slug' => 'vsco',
            'type' => 'social',
            'name' => 'VSCO',
            'hints' => 'Channel Link',
            'instruction' => 'Go to your profile and press “Edit”. You will see your profile link on the top left area of the screen where you can copy it and paste it here.',
            'image' => 'vsco.png',
            'baseURL' => '',
            'profileURL' => 'vsco://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'vscoB.png',
            'roundImage' => 'vscoR.png',
            'roundBlurImage' => 'vscoBR.png'
        ],[
            'id' => '25',
            'slug' => 'whatsapp',
            'type' => 'contact',
            'name' => 'Whats App',
            'hints' => 'Phone Number',
            'instruction' => 'Open WhatsApp and go to settings. Tap your profile at the top and copy/paste number. Include your country code!',
            'image' => 'whatsapp.png',
            'baseURL' => 'https://api.whatsapp.com/send?phone=',
            'profileURL' => 'https://api.whatsapp.com/send?phone=',
            'inputType' => 'phone',
            'status' => '1',
            'blurImage' => 'whatsappB.png',
            'roundImage' => 'whatsappR.png',
            'roundBlurImage' => 'whatsappBR.png'
        ],[
            'id' => '26',
            'slug' => 'yelp',
            'type' => 'business',
            'name' => 'Yelp',
            'hints' => 'Yelp profile url',
            'instruction' => 'Go to the business profile you want to share, press “Share”. Then, copy the link from the popup and paste it here.',
            'image' => 'yelp.png',
            'baseURL' => '',
            'profileURL' => '',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'yelpB.png',
            'roundImage' => 'yelpR.png',
            'roundBlurImage' => 'yelpBR.png'
        ],[
            'id' => '27',
            'slug' => 'youtube',
            'type' => 'social',
            'name' => 'Youtube',
            'hints' => 'Channel Link',
            'instruction' => 'Go to your channel or video. Tap the three dots in the top right corner and tap share. Copy/paste the link here.',
            'image' => 'youtube.png',
            'baseURL' => '',
            'profileURL' => 'youtube://',
            'inputType' => 'other',
            'status' => '1',
            'blurImage' => 'youtubeB.png',
            'roundImage' => 'youtubeR.png',
            'roundBlurImage' => 'youtubeBR.png'
        ]
        ];
        $this->db->table('tbl_plateforms')->insertBatch($data);
        echo $this->db->getLastQuery();
                /*$this->db->table'tbl_socialLinks'->insertBatch'data;
                $db = \Config\Database::connect'
                $db->query'INSERT INTO `tbl_plateforms` 'slug`, `type`, `name`, `hints`, `instruction`, `image`, `baseURL`, `profileURL`,`inputType`,`status` VALUES
'applemusic', 'portfolio', 'Apple Music', 'Playlist / Album Link', 'Pick your favorite playlist/track/album and tap three dots in the top right corner. Tap share and copy/paste link here.', 'applemusic.png', NULL, NULL,'other',1,
'behance', 'portfolio', 'Behance', 'Username', 'Navigate to your avatar in the top right corner, a drop-down menu will appear. Click Settings. Click the Account Information tab.', 'behance.png', 'https://', NULL,'other',1,
'daviplata', 'finance', 'Daviplata', 'Link', ], 'daviplata.png', NULL, 'daviplata://','other',1,
'email', 'contact', 'Email', 'Email', 'Input your email address. This email can be the same of different from the one used for your account signup.', 'email.png', 'mailto:', 'mailto:','email',1,
'facebook', 'social', 'Facebook', 'Facebook Profile Link', 'Go to facebook and open your Facebook profile or page. Under your name there is three dotes, click on it. Then copy your profile link and paste the link here.', 'facebook.png', 'https://www.facebook.com/', 'fb://facewebmodal/f?href=','other',1,
'github', 'portfolio', 'Github', 'Github Link', 'Tap in your profile icon and it will show you your username as “Signed in as user_name”. Copy your username and paste it here.', 'github.png', NULL, 'github://','other',1,
'gmail', 'contact', 'Gmail', 'Email ID', 'Input your email address. This email can be the same of different from the one used for your account signup.', 'gmail.png', NULL, 'gmail://','email',1,
'instagram', 'social', 'Instagram', 'Username without @', 'Open the Instagram app and go to your profile. Your Instagram username will be at the top of your screen.', 'instagram.png', 'https://www.instagram.com/', 'instagram://user?username=','other',1,
'link', 'other', 'Link', 'Custom link', 'Open your desired website and copy/paste the url here.', 'link.png', NULL, NULL,'other',1,
'linkedin', 'social', 'LinkedIn', 'Linkedin Profile url', 'Go to your Linkedin profile and scroll down to the “contact” section. Find your Linkedin profile link and copy/paste here!', 'linkedin.png', 'https://www.linkedin.com/in/', 'linkedin://','other',1,
'maps', 'business', 'Maps', 'Address Here', 'Open Apple Maps and find the Location. Tap the share button in the top right and copy here!', 'maps.png', 'http://maps.google.co.in/maps?q=', 'http://maps.google.co.in/maps?q=','other',1,
'medium', 'portfolio', 'Medium', 'Medium Link', 'Tap in your profile and then select “Settings” from the 3 dots on the top right corner. Then tap in “Account” and you should see your medium URL. Copy and paste it here', 'medium.png', NULL, 'medium://','other',1,
'nequi', 'finance', 'Nequi', 'Nequi Link', ], 'nequi.png', NULL, 'nequi://','other',1,
'outlook', 'contact', 'Outlook', 'Email Address', 'Input your email address. This email can be the same of different from the one used for your account signup.', 'outlook.png', NULL, 'outlook://','email',1,
'paypal', 'finance', 'Paypal', 'Email Address or Payment Link', 'Go to setting. Then to paypal.me and tap “Create your PayPal.Me Link” Copy/paste here! 'xample: paypal.me/username', 'paypal.png', 'https://www.paypal.me/', 'https://www.paypal.com/paypalme/','other',1,
'phone', 'contact', 'Phone', 'Phone Number', 'Enter your phone number. Make sure to include your country code!', 'phone.png', 'tel:', 'tel:','phone',1,
'pinterest', 'social', 'Pinterest', 'Username', 'Click on your profile picture at the top left corner of your screen. Your username can be found under your full name, preceded by “@”. 'on’t include the @ here', 'pinterest.png', 'https://www.pinterest.com/', 'pinterest://www.pinterest.com/','other',1,
'soundcloud', 'portfolio', 'Soundcloud', 'SoundCloud @Username', 'Open the Soundcloud app and go to library then Click on Profile pic at top Right corner.Cick on Profile tab.There share button Click on it And  Copy and paste here.', 'soundcloud.png', NULL, NULL,'other',1,
'spotify', 'portfolio', 'Spotify', 'Username', 'Open Spotify and click a song, album, artist, or playlist. Click the three dots in the top right corner, click share, click Copy Link, and paste the link here.', 'spotify.png', 'https://open.spotify.com/user/', 'open.spotify.com/','other',1,
'tiktok', 'social', 'Tiktok', 'Username without @', 'Open TikTok and go to the “me” tab. Your TikTok username is under your profile picture.', 'tiktok.png', 'https://www.tiktok.com/', 'https://www.tiktok.com/@','other',1,
'tripadvisor', 'business', 'Trip Advisor', 'Trip advisor profile url', 'Go to the listing you want to share, tapp on the share icon and press “Copy Link”. Paste the listing’s link here.', 'tripadvisor.png', NULL, NULL,'other',1,
'twitch', 'social', 'Twitch', 'Username without @', 'Open Twitch and click the profile icon in the top left corner. Your username is at the top.', 'twitch.png', NULL, NULL,'other',1,
'twitter', 'social', 'Twitter', 'Username without @', 'Open the Twitter app and tap your profile picture in the top left corner.Your Twitter username will be in grey with an @ sign.', 'twitter.png', 'https://twitter.com/', 'twitter://user?screen_name=','other',1,
'vsco', 'social', 'VSCO', 'Channel Link', 'Go to your profile and press “Edit”. You will see your profile link on the top left area of the screen where you can copy it and paste it here.', 'vsco.png', NULL, 'vsco://','other',1,
'whatsapp', 'contact', 'Whats App', 'Phone Number', 'Open WhatsApp and go to settings. Tap your profile at the top and copy/paste number. Include your country code!', 'whatsapp.png', 'https://api.whatsapp.com/send?phone=', 'https://api.whatsapp.com/send?phone=','phone',1,
'yelp', 'business', 'Yelp', 'Yelp profile url', 'Go to the business profile you want to share, press “Share”. Then, copy the link from the popup and paste it here.', 'yelp.png', NULL, NULL,'other',1,
'youtube', 'social', 'Youtube', 'Channel Link', 'Go to your channel or video. Tap the three dots in the top right corner and tap share. Copy/paste the link here.', 'youtube.png', NULL, 'youtube://','other',1";*/
   //echo $db->getLastQuery'
   
    }
}





